name: Bi-daily CJEU Update

on:
  schedule:
    - cron: '0 9/6 * * *'  # Every 6 hours starting at 9:00 AM every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-curia:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Update Script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python CJEU_Scraper.py
